# -*- coding: utf-8 -*-
"""Analysis of a super store

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u0fUJugEjbCTJ5c8ZltZT8zbtv80O6qp
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("DoctorVisits - DA.csv")
print(df.head(15))

df.info()

#Find out the total no:of people based on their count of illness
df["illness"].value_counts()

"""Visualize and analyse the maximum,minimum and medium income"""

y = list(df.income)
plt.boxplot(y)
plt.show()

"""Find out the no of days of reduced activity of male and female seperately due to illness"""

df.groupby(['gender','reduced']).mean()

"""Visualize is there is any missing values in the dataset based on a heat map"""

sns.heatmap(df.isnull(),cbar=False,cmap='viridis')

"""Find out the correlation between variables in the given dataset correlation between different variables"""

plt.figure(figsize=(10,10))
sns.heatmap(df.corr(),cbar=True,annot=True,cmap='Blues')

"""Analyse how the income of a patient affects the no of visits to the hospital"""

plt.figure(figsize=(10,10))
plt.scatter(x='income',y='visits',data=df)
plt.xlabel('income')
plt.ylabel('visits')

"""Count and visualize the number of males and females affected by illness"""

sns.histplot(df.gender,bins=2)

"""Visualize the percentage of people getting govt health insurance due to low income,due to old age and also the percentage of people having private health insurance"""

label=['yes','no']
Y=df[df['freepoor' ]=='yes']
N=df[df['freepoor']=='no' ]
x = [Y.shape[0],N.shape[0]]
plt.figure(figsize=(5,5))
plt.pie(x, labels=label)
plt.title("%% of people getting govt health Insurance due to low income")
plt.show()
#% of people having private Insurance
Y = df[df['private']=='yes']
N = df[df['private']=='no']
x = [Y.shape[0],N.shape[0]]
plt.figure(figsize=(5,5))
plt.pie(x, labels=label)
plt.title("% of people having private health Insurance ")
plt.show()
#% of people getting govt Insurance due to old age, disability or veteran status
Y = df[df['freerepat']=='yes']
N=df[df['freerepat']=='no']
x = [Y.shape[0],N.shape[0]]
plt.figure(figsize=(5,5))
plt.pie(x, labels=label)
plt.title("% of people getting govt health Insurance due to old age, disability or veteran status ")
plt.show()

"""Plot a horizontal bar chart to analyze the reduced days of activity due to illness based on Gender"""

db=df.groupby('gender')['reduced'].sum().to_frame().reset_index()
#Creating the bar chart
plt.barh(db['gender'], db['reduced'],color = ['cornflowerblue','lightseagreen'])
#Adding the aesthetics
plt.title('Bar Chart')
plt.xlabel("gender")
plt.ylabel('reduced activity')
#Show the plot
plt.show()